# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build Status

on:
  push:
    branches: [ dev , qa , prod , main]

jobs:
  build:

    runs-on: [ self-hosted, pythonX ]

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9] # add or remove desired python versions here

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install flake8 pytest-cov coveralls
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest-cov
        run: |
          source venv/bin/activate
          coverage run -m pytest
          coverage report -m
      # Coveralls requires a pro account. Could be nice to have in the future
#      - name: Send coveralls
#        run: |
#          coveralls
